version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G101  # False positives on URL constants and test fixtures
        - G104  # Covered by errcheck or intentionally ignored (audit log writes)
        - G115  # Integer overflow: bounded by MaxRetries constant
        - G204  # Subprocess launch for browser open (oauth login flow, user-initiated)
        - G304  # File paths from config/env, not user input
    staticcheck:
      checks:
        - "all"
        - "-QF*"  # Quick-fix suggestions are style preferences, not bugs
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gosec
      # G117: struct fields named AccessToken/RefreshToken/ClientSecret are not hardcoded secrets
      - text: "G117"
        linters:
          - gosec
      # G704: httpClient.Do calls go to Miro API base URL, not arbitrary targets
      - text: "G704"
        linters:
          - gosec
      # G705: all user-facing values are html.EscapeString'd or JSON-marshaled
      - text: "G705"
        linters:
          - gosec
    paths:
      - vendor
